name: base
channels:
  - conda-forge
dependencies:
# development tools
  - cmake<4.0 # some libraries still require 3.5.x
  - make
  - m4
  - pkg-config
  - vim
  - nvim
  - rsync
  - openssh
  - tree
# python packages
  - pytest
  - pytest-cov
  - pyyaml
# libraries
  - lapack
  - blas
  - hdf5=*=*openmpi*
  - netcdf-fortran=*=*openmpi*
  - libpnetcdf=*=*openmpi*
  - esmf=*=*openmpi*
  - openmpi
  - gcc_linux-64
  - gxx_linux-64
  - gfortran_linux-64
  - gcc=12.*
  - gxx=12.*
  - gfortran=12.*
  - compilers
  - c-compiler
  - cxx-compiler
  - fortran-compiler
prefix: /opt/conda
