name: autotools_2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CC: mpicc
      FC: mpifort
      CPPFLAGS: "-I/usr/include -I/usr/local/include"
#      CFLAGS: "-std=c99  -fsanitize=address -fno-omit-frame-pointer -Werror"
#      FFLAGS: "-fsanitize=address -fno-omit-frame-pointer"
#      FCFLAGS: "-fsanitize=address -fno-omit-frame-pointer -Werror"

    steps:
    - uses: actions/checkout@v2
    - name: Installs
      run: |
        sudo apt-get install netcdf-bin libnetcdf-dev doxygen graphviz wget gfortran libjpeg-dev libz-dev openmpi-bin libopenmpi-dev 

    - name: pnetcdf build
      run: |
        wget https://parallel-netcdf.github.io/Release/pnetcdf-1.11.0.tar.gz 
        tar -xzvf pnetcdf-1.11.0.tar.gz
        ls -l
        pushd pnetcdf-1.11.0
        ./configure --prefix=/usr --enable-shared --disable-cxx
        make
        sudo make install
        popd

    - name: autoreconf
      run: autoreconf -i
    - name: configure
      run: |
        doxygen --version
        ./configure --enable-docs
        cat config.log
    - name: make check
      run: make check
