---   # cmake build without netcdf integration
name: cmake_ubuntu-latest

on:
  push:
    branches:
      - mainnot
  pull_request:
    branches:
      - mainnot

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CC: mpicc
      FC: mpifort
      CPPFLAGS: "-I/usr/include -I/usr/local/include -I${GITHUB_WORKSPACE}/pnetcdf/include"
      LDFLAGS: "-L${GITHUB_WORKSPACE}/pnetcdf/lib -L/usr/lib"
      LD_LIBRARY_PATH: "${GITHUB_WORKSPACE}/pnetcdf/lib:/usr/lib"
      PNETCDF_VERSION: checkpoint.1.12.3
      FCFLAGS: "-fallow-argument-mismatch"
    steps:
      - uses: actions/checkout@v3
      - name: Installs
        run: |
          set -x
          #sudo gem install apt-spy2
          #sudo apt-spy2 check
          #sudo apt-spy2 fix --commit
          # after selecting a specific mirror, we need to run 'apt-get update'
          sudo apt-get update
          sudo apt-get install netcdf-bin libnetcdf-dev doxygen graphviz wget gfortran libjpeg-dev libz-dev openmpi-bin libopenmpi-dev

      - name: cache-pnetcdf
        id: cache-pnetcdf
        uses: actions/cache@v3
        with:
          path: ~/pnetcdf
          key: pnetcdf-${{ runner.os }}-${{ env.PNETCDF_VERSION }}

      - name: Build PNetCDF
        if: steps.cache-pnetcdf.outputs.cache-hit != 'true'
        uses: ./.github/actions/buildpnetcdf
        with:
          pnetcdf_version: ${{ env.PNETCDF_VERSION }}
          install_prefix: $HOME/pnetcdf

      - name: cmake build
        uses: ./.github/actions/parallelio_cmake
        with:
          parallelio_version: ${{ env.GITHUB_SHA }}
          pnetcdf_include_dir: $GITHUB_WORKSPACE/pnetcdf/include
          pnetcdf_library: $GITHUB_WORKSPACE/pnetcdf/lib/libpnetcdf.so
          netcdf_include_dir: /usr/include
          netcdf_library: /usr/lib/x86_64-linux-gnu/libnetcdf.so
          install_prefix: $GITHUB_WORKSPACE/parallelio
          with_mpiexec: /usr/bin/mpiexec --oversubscribe
      - name: run tests
        run: |
          pushd $GITHUB_WORKSPACE/parallelio-src
          make tests VERBOSE=1
          ctest -VV
